In [1]:
import random
import numpy as np
import matplotlib.pyplot as plt

# This is a bit of magic to make matplotlib figures appear inline in the notebook
# rather than in a new window.

%matplotlib inline
plt.rcParams['figure.figsize'] = (10.0, 8.0) # set default size of plots
plt.rcParams['image.interpolation'] = 'nearest'
plt.rcParams['image.cmap'] = 'gray'

# Some more magic so that the notebook will reload external python modules;
# see http://stackoverflow.com/questions/1907993/autoreload-of-modules-in-ipython

%load_ext autoreload
%autoreload 2

In [17]:
from sklearn import preprocessing, metrics
import utils
import scipy.io
import numpy as np
from linear_classifier import LinearSVM_twoclass

# load the SPAM email training dataset

X,y = utils.load_mat('data/spamTrain.mat')
yy = np.ones(y.shape)
yy[y==0] = -1
print X.shape
print yy[:6,]
print yy.shape
print X[:6,:13]

test_data = scipy.io.loadmat('data/spamTest.mat')
X_test = test_data['Xtest']
y_test = test_data['ytest'].flatten()
yy_test=np.ones(y_test.shape)
yy_test[y_test==0]=-1
print X_test.shape
print y_test.shape
print X_test[:6,:13]
print y_test[:6,]

##################################################################################
#  YOUR CODE HERE for training the best performing SVM for the data above.       #
#  what should C be? What should num_iters be? Should X be scaled?               #
#  should X be kernelized? What should the learning rate be? What should the     #
#  number of iterations be?                                                      #
##################################################################################
Cvals = [10,30,50,100]
iterationvals=[2000,5000,10000]
learning_ratevals=[1e-3,1e-2,1e-1]

best_C=Cvals[0]
best_iteration=iterationvals[0]
best_learning_rate=learning_ratevals[0]
best_val_acc=0

for C in Cvals:
    for iteration in iterationvals:
        for learning_rate in learning_ratevals:
            print "Training with C = {} and iteration = {}, learning_rate = {}".format(C,iteration,learing_rate)
            svm = LinearSVM_twoclass()
            svm.theta = np.zeros((X.shape[1],))
            svm.train(X,yy,learning_rate=learning_rate,reg=C,num_iters=iteration,verbose=False)
            yyval_pred = svm.predict(X_test)
            val_acc=np.mean(yyval_pred==yy_test)
            print "When C={},iteration={},learning_rate={},and accuray={}".format(C,iteration,learning_rate,val_acc)
            if val_acc>=best_val_acc:
                best_val_acc=val_acc
                best_C=C
                best_iteration=iteration
                best_learning_rate=learning_rate


print "The best_C={}, best_iteration={},best_learing_rate={},best_val_acc={}".format(best_C,best_iteration,best_learning_rate,best_val_acc)




(4000, 1899)
[ 1.  1. -1. -1. -1. -1.]
(4000,)
[[0 0 0 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 0 0 0 1 1 0 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
(1000, 1899)
(1000,)
[[0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0]]
[1 0 0 1 1 1]
Training with C = 10 and iteration = 2000, learning_rate = 0.001
When C=10,iteration=2000,learning_rate=0.001,and accuray=0.98
Training with C = 10 and iteration = 2000, learning_rate = 0.001
When C=10,iteration=2000,learning_rate=0.01,and accuray=0.992
Training with C = 10 and iteration = 2000, learning_rate = 0.001
When C=10,iteration=2000,learning_rate=0.1,and accuray=0.988
Training with C = 10 and iteration = 5000, learning_rate = 0.001
When C=10,iteration=5000,learning_rate=0.001,and accuray=0.99
Training with C = 10 and iteration = 5000, learning_rate = 0.

In [18]:
from sklearn import preprocessing, metrics
import utils
import scipy.io
import numpy as np
from linear_classifier import LinearSVM_twoclass

# load the SPAM email training dataset

X,y = utils.load_mat('data/spamTrain.mat')
yy = np.ones(y.shape)
yy[y==0] = -1


test_data = scipy.io.loadmat('data/spamTest.mat')
X_test = test_data['Xtest']
y_test = test_data['ytest'].flatten()
yy_test=np.ones(y_test.shape)
yy_test[y_test==0]=-1


##################################################################################
#  YOUR CODE HERE for training the best performing SVM for the data above.       #
#  what should C be? What should num_iters be? Should X be scaled?               #
#  should X be kernelized? What should the learning rate be? What should the     #
#  number of iterations be?                                                      #
##################################################################################
Cvals = [0.01,0.1,1,10]
iterationvals=[2000,5000,10000]
learning_ratevals=[1e-3,1e-2,1e-1]

best_C=Cvals[0]
best_iteration=iterationvals[0]
best_learning_rate=learning_ratevals[0]
best_val_acc=0

for C in Cvals:
    for iteration in iterationvals:
        for learning_rate in learning_ratevals:
            print "Training with C = {} and iteration = {}, learning_rate = {}".format(C,iteration,learing_rate)
            svm = LinearSVM_twoclass()
            svm.theta = np.zeros((X.shape[1],))
            svm.train(X,yy,learning_rate=learning_rate,reg=C,num_iters=iteration,verbose=False)
            yyval_pred = svm.predict(X_test)
            val_acc=np.mean(yyval_pred==yy_test)
            print "When C={},iteration={},learning_rate={},and accuray={}".format(C,iteration,learning_rate,val_acc)
            if val_acc>=best_val_acc:
                best_val_acc=val_acc
                best_C=C
                best_iteration=iteration
                best_learning_rate=learning_rate


print "The best_C={}, best_iteration={},best_learing_rate={},best_val_acc={}".format(best_C,best_iteration,best_learning_rate,best_val_acc)



Training with C = 0.01 and iteration = 2000, learning_rate = 0.001
When C=0.01,iteration=2000,learning_rate=0.001,and accuray=0.692
Training with C = 0.01 and iteration = 2000, learning_rate = 0.001
When C=0.01,iteration=2000,learning_rate=0.01,and accuray=0.704
Training with C = 0.01 and iteration = 2000, learning_rate = 0.001
When C=0.01,iteration=2000,learning_rate=0.1,and accuray=0.958
Training with C = 0.01 and iteration = 5000, learning_rate = 0.001
When C=0.01,iteration=5000,learning_rate=0.001,and accuray=0.692
Training with C = 0.01 and iteration = 5000, learning_rate = 0.001
When C=0.01,iteration=5000,learning_rate=0.01,and accuray=0.82
Training with C = 0.01 and iteration = 5000, learning_rate = 0.001
When C=0.01,iteration=5000,learning_rate=0.1,and accuray=0.966
Training with C = 0.01 and iteration = 10000, learning_rate = 0.001
When C=0.01,iteration=10000,learning_rate=0.001,and accuray=0.692
Training with C = 0.01 and iteration = 10000, learning_rate = 0.001
When C=0.01,i

In [ ]:
from sklearn import preprocessing, metrics
import utils
import scipy.io
import numpy as np
from linear_classifier import LinearSVM_twoclass

# load the SPAM email training dataset

X,y = utils.load_mat('data/spamTrain.mat')
yy = np.ones(y.shape)
yy[y==0] = -1

# load the SPAM email test dataset

test_data = scipy.io.loadmat('data/spamTest.mat')
X_test = test_data['Xtest']
y_test = test_data['ytest'].flatten()

##################################################################################
#  YOUR CODE HERE for training the best performing SVM for the data above.       #
#  what should C be? What should num_iters be? Should X be scaled?               #
#  should X be kernelized? What should the learning rate be? What should the     #
#  number of iterations be?                                                      #
##################################################################################
svm = LinearSVM_twoclass()
svm.theta = np.zeros((X.shape[1],))



##################################################################################
# YOUR CODE HERE for testing your best model's performance                       #
# what is the accuracy of your best model on the test set? On the training set?  #
##################################################################################



##################################################################################
# ANALYSIS OF MODEL: Print the top 15 words that are predictive of spam and for  #
# ham. Hint: use the coefficient values of the learned model                     #
##################################################################################
words, inv_words = utils.get_vocab_dict()

##################################################################################
#                    END OF YOUR CODE                                            #
##################################################################################